# Generated by Django 6.0.3 on 2026-05-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('years', models.IntegerField(default=0)),
                ('case_number', models.CharField(blank=True, default='', max_length=100)),
                ('case_type', models.CharField(blank=True, default='', max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
