# Generated by Django 6.0.3 on 2026-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='department',
            field=models.CharField(choices=[('section1', 'القسم الأول'), ('section2', 'القسم الثاني'), ('section3', 'القسم الثالث')], default='section1', max_length=20, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='material',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='material',
            name='age',
            field=models.IntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='material',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='رقم القضية'),
        ),
        migrations.AlterField(
            model_name='material',
            name='case_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='نوع القضية'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='material',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع'),
        ),
        migrations.AlterField(
            model_name='material',
            name='years',
            field=models.IntegerField(default=0, verbose_name='عدد السنوات'),
        ),
    ]
