# Generated by Django 6.0.3 on 2026-05-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_material_department_alter_material_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='years',
        ),
    ]
