# Generated by Django 6.0.3 on 2026-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_remove_material_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date_sessions',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الجلسات'),
        ),
        migrations.AddField(
            model_name='material',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='papers/', verbose_name='الاوراق الخاصة بالمتهم'),
        ),
    ]
